//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCal.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int eventId { get; set; }
        public string title { get; set; }
        public Nullable<bool> allDay { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public string url { get; set; }
        public Nullable<bool> editable { get; set; }
        public string description { get; set; }
        public Nullable<int> id { get; set; }
    }
}
