//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullCal.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> AllDay { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
        public string Url { get; set; }
        public Nullable<bool> Editable { get; set; }
        public string Description { get; set; }
        public Nullable<int> EventId { get; set; }
    }
}
